"""Real-world codon optimization and harmonization test cases.

These sequences are sourced from published scientific literature and
public databases (GenBank/NCBI). They serve as ground-truth test cases
for validating codon optimization tools.

All DNA sequences are 5'->3' coding strand, uppercase.
All protein sequences use standard single-letter amino acid codes.
Stop codons are included in DNA but not in protein sequences.
"""

# =============================================================================
# TEST CASE 1: GFP -> EGFP (Codon optimization + protein engineering)
# =============================================================================
#
# Wild-type GFP from Aequorea victoria (jellyfish) was codon-optimized
# for expression in human/mammalian cells to create EGFP. IMPORTANT:
# EGFP also has protein-level mutations (F64L, S65T plus V2 insertion)
# that improve spectral properties, so this is NOT a pure codon
# optimization. Useful for testing codon usage analysis.
#
# Reference: Yang et al. (1996) Nucleic Acids Res. 24(22):4592-3
#   "Optimized Codon Usage and Chromophore Mutations Provide Enhanced
#   Sensitivity with the Green Fluorescent Protein"
#

GFP_WILD_TYPE = {
    "name": "Wild-type GFP",
    "source_organism": "Aequorea victoria",
    "ncbi_taxonomy_id": 6100,
    "genbank_accession": "L29345.1",
    "cds_length_bp": 717,
    "protein_length_aa": 238,
    "dna_sequence": (
        "ATGAGTAAAGGAGAAGAACTTTTCACTGGAGTTGTCCCAATTCTTGTTGAATTAGATGGCGATGTTAATG"
        "GGCAAAAATTCTCTGTCAGTGGAGAGGGTGAAGGTGATGCAACATACGGAAAACTTACCCTTAAATTTAT"
        "TTGCACTACTGGGAAGCTACCTGTTCCATGGCCAACACTTGTCACTACTTTCTCTTATGGTGTTCAATGC"
        "TTTTCAAGATACCCAGATCATATGAAACAGCATGACTTTTTCAAGAGTGCCATGCCCGAAGGTTATGTAC"
        "AGGAAAGAACTATATTTTACAAAGATGACGGGAACTACAAGACACGTGCTGAAGTCAAGTTTGAAGGTGA"
        "TACCCTTGTTAATAGAATCGAGTTAAAAGGTATTGATTTTAAAGAAGATGGAAACATTCTTGGACACAAA"
        "ATGGAATACAACTATAACTCACATAATGTATACATCATGGCAGACAAACCAAAGAATGGAATCAAAGTTA"
        "ACTTCAAAATTAGACACAACATTAAAGATGGAAGCGTTCAATTAGCAGACCATTATCAACAAAATACTCC"
        "AATTGGCGATGGCCCTGTCCTTTTACCAGACAACCATTACCTGTCCACACAATCTGCCCTTTCCAAAGAT"
        "CCCAACGAAAAGAGAGATCACATGATCCTTCTTGAGTTTGTAACAGCTGCTGGGATTACACATGGCATGG"
        "ATGAACTATACAAATAA"
    ),
    "protein_sequence": (
        "MSKGEELFTGVVPILVELDGDVNGQKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQC"
        "FSRYPDHMKQHDFFKSAMPEGYVQERTIFYKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHK"
        "MEYNYNSHNVYIMADKPKNGIKVNFKIRHNIKDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKD"
        "PNEKRDHMILLEFVTAAGITHGMDELYK"
    ),
}

EGFP_HUMANIZED = {
    "name": "EGFP (Enhanced GFP, human codon-optimized + mutations)",
    "source_organism": "Aequorea victoria (engineered)",
    "target_organism": "Homo sapiens",
    "target_taxonomy_id": 9606,
    "genbank_accession": "U55762 (pEGFP-N1, CDS positions 679-1398)",
    "mutations_vs_wt": "V2 insertion, F64L, S65T, plus other substitutions",
    "cds_length_bp": 720,
    "protein_length_aa": 239,
    "dna_sequence": (
        "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAA"
        "ACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTT"
        "CATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAG"
        "TGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACG"
        "TCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGG"
        "CGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCAC"
        "AAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGG"
        "TGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACAC"
        "CCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAA"
        "GACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCA"
        "TGGACGAGCTGTACAAGTAA"
    ),
    "protein_sequence": (
        "MVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQ"
        "CFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGH"
        "KLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSK"
        "DPNEKRDHMVLLEFVTAAGITLGMDELYK"
    ),
}

# =============================================================================
# TEST CASE 2: GFP Codon Optimization for Low-GC Gram-Positive Bacteria
# =============================================================================
#
# GFP codon-optimized for expression in low-GC gram-positive bacteria
# (B. anthracis, S. aureus). Based on GFPmut1 derivative (same protein as
# EGFP: F64L, S65T, plus other substitutions). This is a microbial target
# example — NOT human/mammalian.
#
# Reference: Sastalla et al. (2009) Appl Environ Microbiol 75(5):1364-73
#   "Codon-Optimized Fluorescent Proteins Designed for Expression in
#   Low-GC Gram-Positive Bacteria"
#

GFPOPT_GRAM_POSITIVE = {
    "name": "GFPopt (codon-optimized for low-GC gram-positive bacteria)",
    "source_organism": "Aequorea victoria (engineered)",
    "target_organism": "Bacillus anthracis / Staphylococcus aureus",
    "target_note": "Optimized for low genomic GC content bacteria",
    "genbank_accession": "FJ169508",
    "cds_length_bp": 717,
    "protein_length_aa": 238,
    "dna_sequence": (
        "ATGTCAAAAGGAGAAGAATTATTTACAGGGGTAGTACCAATTTTAGTAGAACTTGACGGA"
        "GATGTAAATGGACACAAATTTTCAGTATCAGGAGAAGGAGAAGGAGATGCAACATACGGA"
        "AAATTAACACTTAAATTCATTTGTACAACAGGTAAACTACCGGTTCCATGGCCCACACTTG"
        "TGACTACTTTAACATACGGAGTACAATGTTTTTCAAGATATCCAGATCATATGAAACAAC"
        "ACGACTTTTTTAAATCAGCAATGCCTGAAGGATACGTACAAGAAAGAACAATATTTTTTA"
        "AAGATGATGGTAACTATAAAACGAGAGCAGAAGTAAAATTTGAAGGAGATACATTAGTAA"
        "ACAGAATTGAATTAAAAGGAATAGACTTTAAAGAAGATGGAAATATCCTAGGACATAAATT"
        "AGAATACAATTACAACAGTCATAACGTATACATAATGGCAGATAAACAGAAAAATGGAAT"
        "TAAAGTTAACTTTAAAATAAGACACAATATAGAAGACGGATCAGTACAATTAGCAGATCAC"
        "TATCAACAAAATACACCTATCGGAGATGGCCCAGTGCTTCTACCAGATAATCATTACTTAA"
        "GCACGCAAAGCGCTTTATCTAAAGACCCAAATGAAAAAAGAGACCACATGGTATTATTAGAA"
        "TTCGTAACAGCAGCAGGAATTACACACGGAATGGATGAATTATATAAGTAA"
    ),
    "protein_sequence": (
        "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTL"
        "VTTLTYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVN"
        "RIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHY"
        "QQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
    ),
}

# =============================================================================
# TEST CASE 3: GFP Codon Optimization for S. cerevisiae (Yeast)
# =============================================================================
#
# yEGFP3 — GFP with all codons optimized for S. cerevisiae and C. albicans.
# Contains S65G, S72A chromophore mutations (different from EGFP's F64L, S65T).
# Same backbone as wild-type GFP (238 aa, no V2 insertion).
#
# Reference: Cormack et al. (1997) Microbiology 143:303-311
#   "FACS-optimized mutants of the green fluorescent protein (GFP)"
#

YEGFP3_YEAST = {
    "name": "yEGFP3 (yeast codon-optimized GFP)",
    "source_organism": "Aequorea victoria (engineered)",
    "target_organism": "Saccharomyces cerevisiae",
    "target_taxonomy_id": 4932,
    "genbank_accession": "U73901.1",
    "cds_length_bp": 717,
    "protein_length_aa": 238,
    "mutations_vs_wt": "S65G, S72A (chromophore mutations)",
    "dna_sequence": (
        "ATGTCTAAAGGTGAAGAATTATTCACTGGTGTTGTCCCAATTTTGGTTGAATTAGATGGT"
        "GATGTTAATGGTCACAAATTTTCTGTCTCCGGTGAAGGTGAAGGTGATGCTACTTACGGT"
        "AAATTGACCTTAAAATTTATTTGTACTACTGGTAAATTGCCAGTTCCATGGCCAACCTTAG"
        "TCACTACTTTCGGTTATGGTGTTCAATGTTTTGCTAGATACCCAGATCATATGAAACAAC"
        "ATGACTTTTTCAAGTCTGCCATGCCAGAAGGTTATGTTCAAGAAAGAACTATTTTTTTCAA"
        "AGATGACGGTAACTACAAGACCAGAGCTGAAGTCAAGTTTGAAGGTGATACCTTAGTTAAT"
        "AGAATCGAATTAAAAGGTATTGATTTTAAAGAAGATGGTAACATTTTAGGTCACAAATTGG"
        "AATACAACTATAACTCTCACAATGTTTACATCATGGCTGACAAACAAAAGAATGGTATCAAA"
        "GTTAACTTCAAAATTAGACACAACATTGAAGATGGTTCTGTTCAATTAGCTGACCATTATCA"
        "ACAAAATACTCCAATTGGTGATGGTCCAGTCTTGTTACCAGACAACCATTACTTATCCACTC"
        "AATCTGCCTTATCCAAAGATCCAAACGAAAAGAGAGACCACATGGTCTTGTTAGAATTTGTT"
        "ACTGCTGCTGGTATTACCCATGGTATGGATGAATTGTACAAATAA"
    ),
    "protein_sequence": (
        "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTL"
        "VTTFGYGVQCFARYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVN"
        "RIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHY"
        "QQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
    ),
}

# =============================================================================
# TEST CASE 4: Human Insulin Codon Optimization (Human -> E. coli)
# =============================================================================
#
# Human preproinsulin (110 aa) vs E. coli codon-optimized M-proinsulin
# (87 aa). The E. coli version encodes proinsulin with an N-terminal
# Met, but without the signal peptide. These encode DIFFERENT proteins
# (different lengths), but share the proinsulin core sequence.
#
# Reference: Gardner et al. (2009) GenBank AB501190
#   Goeddel et al. (1979) PNAS 76(1):106-110
#   "Expression in E. coli of chemically synthesized genes for human insulin"
#

INSULIN_HUMAN_NATIVE = {
    "name": "Human preproinsulin (native codons)",
    "source_organism": "Homo sapiens",
    "ncbi_taxonomy_id": 9606,
    "genbank_accession": "NM_000207.3",
    "cds_note": "Positions 60-392 in mRNA; includes signal peptide + proinsulin",
    "cds_length_bp": 333,
    "protein_length_aa": 110,
    "dna_sequence": (
        "ATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAG"
        "CCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGG"
        "CTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGG"
        "GGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAAC"
        "AATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACTAG"
    ),
    "protein_sequence": "MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN",
}

INSULIN_ECOLI_OPTIMIZED = {
    "name": "Human M-proinsulin (E. coli codon-optimized)",
    "source_organism": "Homo sapiens (synthetic)",
    "target_organism": "Escherichia coli",
    "target_taxonomy_id": 562,
    "genbank_accession": "AB501190",
    "cds_note": "Positions 9-272; Met + proinsulin (no signal peptide)",
    "cds_length_bp": 264,
    "protein_length_aa": 87,
    "dna_sequence": (
        "ATGTTTGTTAACCAGCATCTGTGCGGGTCGCACTTAGTAGAAGCCCTGTATCTGGTCTGTGGTGAACGCG"
        "GTTTTTTCTATACCCCGAAAACTCGTCGCGAAGCGGAAGATCTGCAGGTGGGCCAAGTTGAACTGGGTGG"
        "CGGTCCAGGCGCTGGTAGCTTGCAGCCGTTAGCACTGGAAGGGAGTTTGCAAAAACGTGGCATCGTGGAA"
        "CAGTGCTGTACGTCTATTTGTTCCCTGTACCAGCTGGAAAATTACTGCAACTAG"
    ),
    "protein_sequence": "MFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN",
}

# =============================================================================
# TEST CASE 3: MSP1-42 Codon HARMONIZATION (P. falciparum -> E. coli)
# =============================================================================
#
# This is a textbook codon HARMONIZATION example. The native
# P. falciparum MSP1-42 sequence (AT-rich, ~80% AT) was recoded for
# E. coli using the codon harmonization algorithm, which matches codon
# usage frequencies (not just selecting the most frequent codon).
#
# KEY PROPERTIES:
#   - Protein: IDENTICAL (0 amino acid differences over 355 residues)
#   - DNA: 310 nucleotide changes in 1065 bp (29.1%% differ)
#   - DNA identity: 70.9%%
#
# Reference: Angov et al. (2008) PLoS ONE 3(5):e2189
#   "Heterologous Protein Expression Is Enhanced by Harmonizing the
#   Codon Usage Frequencies of the Target Gene with those of the
#   Expression Host"
#

MSP142_NATIVE = {
    "name": "MSP1-42 FVO (native P. falciparum codons)",
    "source_organism": "Plasmodium falciparum",
    "strain": "Vietnam Oak Knoll (FVO)",
    "ncbi_taxonomy_id": 5833,
    "genbank_accession": "L20092",
    "cds_note": "Partial CDS, no start Met or stop codon in this fragment",
    "length_bp": 1065,
    "dna_sequence": (
        "GCAGTAACTCCTTCCGTAATTGATAACATACTTTCTAAAATTGAAAATGAATATGAGGTTTTATATTTAA"
        "AACCTTTAGCAGGTGTTTATAGAAGTTTAAAAAAACAATTAGAAAATAACGTTATGACATTTAATGTTAA"
        "TGTTAAGGATATTTTAAATTCACGATTTAATAAACGTGAAAATTTCAAAAATGTTTTAGAATCAGATTTA"
        "ATTCCATATAAAGATTTAACATCAAGTAATTATGTTGTCAAAGATCCATATAAATTTCTTAATAAAGAAA"
        "AAAGAGATAAATTCTTAAGCAGTTATAATTATATTAAGGATTCAATAGATACGGATATAAATTTTGCAAA"
        "TGATGTTCTTGGATATTATAAAATATTATCCGAAAAATATAAATCAGATTTAGATTCAATTAAAAAATAT"
        "ATCAACGACAAACAAGGTGAAAATGAGAAATACCTTCCCTTTTTAAACAATATTGAGACCTTATATAAAA"
        "CAGTTAATGATAAAATTGATTTATTTGTAATTCATTTAGAAGCAAAAGTTCTAAATTATACATATGAGAA"
        "ATCAAACGTAGAAGTTAAAATAAAAGAACTTAATTACTTAAAAACAATTCAAGACAAATTGGCAGATTTT"
        "AAAAAAAATAACAATTTCGTTGGAATTGCTGATTTATCAACAGATTATAACCATAATAACTTATTGACAA"
        "AGTTCCTTAGTACAGGTATGGTTTTTGAAAATCTTGCTAAAACCGTTTTATCTAATTTACTTGATGGAAA"
        "CTTGCAAGGTATGTTAAACATTTCACAACACCAATGCGTAAAAAAACAATGTCCACAAAATTCTGGATGT"
        "TTCAGACATTTAGATGAAAGAGAAGAATGTAAATGTTTATTAAATTACAAACAAGAAGGTGATAAATGTG"
        "TTGAAAATCCAAATCCTACTTGTAACGAAAATAATGGTGGATGTGATGCAGATGCCAAATGTACCGAAGA"
        "AGATTCAGGTAGCAACGGAAAGAAAATCACATGTGAATGTACTAAACCTGATTCTTATCCACTTTTCGAT"
        "GGTATTTTCTGCAGT"
    ),
    "protein_sequence": "AVTPSVIDNILSKIENEYEVLYLKPLAGVYRSLKKQLENNVMTFNVNVKDILNSRFNKRENFKNVLESDLIPYKDLTSSNYVVKDPYKFLNKEKRDKFLSSYNYIKDSIDTDINFANDVLGYYKILSEKYKSDLDSIKKYINDKQGENEKYLPFLNNIETLYKTVNDKIDLFVIHLEAKVLNYTYEKSNVEVKIKELNYLKTIQDKLADFKKNNNFVGIADLSTDYNHNNLLTKFLSTGMVFENLAKTVLSNLLDGNLQGMLNISQHQCVKKQCPQNSGCFRHLDEREECKCLLNYKQEGDKCVENPNPTCNENNGGCDADAKCTEEDSGSNGKKITCECTKPDSYPLFDGIFCS",
}

MSP142_HARMONIZED = {
    "name": "MSP1-42 FVO (codon-harmonized for E. coli)",
    "source_organism": "Plasmodium falciparum (synthetic)",
    "target_organism": "Escherichia coli",
    "target_taxonomy_id": 562,
    "genbank_accession": "DQ926900",
    "cds_note": "Full construct has N-terminal His-tag (MAHHHHHHPGGSGSGT). MSP1-42 CDS starts at bp 49.",
    "full_length_bp": 1113,
    "msp142_portion_length_bp": 1065,
    "dna_sequence_full_construct": (
        "ATGGCACACCATCATCATCATCATCCCGGGGGATCCGGTTCTGGTACCGCTGTTACGCCATCGGTTATTG"
        "ACAATATCCTCAGCAAAATTGAAAACGAATACGAGGTTCTGTACCTGAAACCACTGGCTGGCGTTTACCG"
        "TTCTCTGAAAAAACAGCTGGAAAACAATGTTATGACCTTCAACGTTAACGTTAAGGACATTCTGAACAGC"
        "CGCTTCAACAAACGCGAAAACTTTAAAAACGTTCTGGAAAGCGACCTGATTCCATACAAAGACCTGACCA"
        "GCTCTAACTACGTTGTCAAAGACCCATACAAATTCCTCAACAAAGAAAAACGTGACAAATTTCTGTCGTC"
        "TTACAACTACATTAAGGACAGCATCGACACGGACATCAACTTCGCTAACGACGTTCTCGGCTACTACAAA"
        "ATCCTGTCGGAAAAATACAAAAGCGACCTGGACAGCATTAAAAAATACATTAATGATAAACAGGGCGAAA"
        "ACGAGAAATATCTCCCTTTCCTGAATAACATTGAGACGCTGTACAAAACCGTTAACGACAAAATTGACCT"
        "GTTCGTTATTCACCTGGAAGCTAAAGTTCTCAACTACACCTACGAGAAAAGCAATGTTGAAGTTAAAATC"
        "AAAGAACTCAACTATCTGAAAACCATTCAGGATAAACTCGCTGACTTCAAAAAAAACAATAACTTTGTTG"
        "GCATTGCTGACCTGAGCACCGACTACAATCACAACAATCTGCTCACCAAGTTTCTCTCTACCGGCATGGT"
        "TTTCGAAAACCTCGCTAAAACGGTTCTGAGCAACCTGCTCGACGGCAATCTCCAGGGCATGCTGAATATT"
        "AGCCAGCATCAGTGTGTTAAAAAACAGTGCCCACAGAACAGCGGCTGCTTTCGTCACCTGGACGAACGTG"
        "AAGAATGCAAATGCCTGCTGAACTATAAACAGGAAGGCGACAAATGCGTTGAAAACCCAAACCCAACTTG"
        "CAATGAAAACAACGGCGGCTGCGACGCTGACGCCAAATGCACGGAAGAAGACAGCGGCTCGAATGGCAAG"
        "AAAATTACCTGCGAATGCACTAAACCAGACAGCTACCCACTCTTTGACGGCATTTTCTGCAGT"
    ),
    "dna_sequence_msp142_only": (
        "GCTGTTACGCCATCGGTTATTGACAATATCCTCAGCAAAATTGAAAACGAATACGAGGTTCTGTACCTGA"
        "AACCACTGGCTGGCGTTTACCGTTCTCTGAAAAAACAGCTGGAAAACAATGTTATGACCTTCAACGTTAA"
        "CGTTAAGGACATTCTGAACAGCCGCTTCAACAAACGCGAAAACTTTAAAAACGTTCTGGAAAGCGACCTG"
        "ATTCCATACAAAGACCTGACCAGCTCTAACTACGTTGTCAAAGACCCATACAAATTCCTCAACAAAGAAA"
        "AACGTGACAAATTTCTGTCGTCTTACAACTACATTAAGGACAGCATCGACACGGACATCAACTTCGCTAA"
        "CGACGTTCTCGGCTACTACAAAATCCTGTCGGAAAAATACAAAAGCGACCTGGACAGCATTAAAAAATAC"
        "ATTAATGATAAACAGGGCGAAAACGAGAAATATCTCCCTTTCCTGAATAACATTGAGACGCTGTACAAAA"
        "CCGTTAACGACAAAATTGACCTGTTCGTTATTCACCTGGAAGCTAAAGTTCTCAACTACACCTACGAGAA"
        "AAGCAATGTTGAAGTTAAAATCAAAGAACTCAACTATCTGAAAACCATTCAGGATAAACTCGCTGACTTC"
        "AAAAAAAACAATAACTTTGTTGGCATTGCTGACCTGAGCACCGACTACAATCACAACAATCTGCTCACCA"
        "AGTTTCTCTCTACCGGCATGGTTTTCGAAAACCTCGCTAAAACGGTTCTGAGCAACCTGCTCGACGGCAA"
        "TCTCCAGGGCATGCTGAATATTAGCCAGCATCAGTGTGTTAAAAAACAGTGCCCACAGAACAGCGGCTGC"
        "TTTCGTCACCTGGACGAACGTGAAGAATGCAAATGCCTGCTGAACTATAAACAGGAAGGCGACAAATGCG"
        "TTGAAAACCCAAACCCAACTTGCAATGAAAACAACGGCGGCTGCGACGCTGACGCCAAATGCACGGAAGA"
        "AGACAGCGGCTCGAATGGCAAGAAAATTACCTGCGAATGCACTAAACCAGACAGCTACCCACTCTTTGAC"
        "GGCATTTTCTGCAGT"
    ),
    "protein_sequence_msp142_only": "AVTPSVIDNILSKIENEYEVLYLKPLAGVYRSLKKQLENNVMTFNVNVKDILNSRFNKRENFKNVLESDLIPYKDLTSSNYVVKDPYKFLNKEKRDKFLSSYNYIKDSIDTDINFANDVLGYYKILSEKYKSDLDSIKKYINDKQGENEKYLPFLNNIETLYKTVNDKIDLFVIHLEAKVLNYTYEKSNVEVKIKELNYLKTIQDKLADFKKNNNFVGIADLSTDYNHNNLLTKFLSTGMVFENLAKTVLSNLLDGNLQGMLNISQHQCVKKQCPQNSGCFRHLDEREECKCLLNYKQEGDKCVENPNPTCNENNGGCDADAKCTEEDSGSNGKKITCECTKPDSYPLFDGIFCS",
}

# =============================================================================
# TEST CASE 4: SpCas9 Codon Optimization (S. pyogenes -> Human)
# =============================================================================
#
# The S. pyogenes Cas9 was human codon-optimized for mammalian cell
# expression. This is a large protein (1368 aa, 4107 bp) and represents
# a pure synonymous codon optimization (identical protein).
#
# KEY PROPERTIES:
#   - Protein: IDENTICAL (0 amino acid differences over 1368 residues)
#   - DNA: 1253 nucleotide changes in 4107 bp (30.5%% differ)
#   - DNA identity: 69.5%%
#
# Reference: Cong et al. (2013) Science 339(6121):819-23
#   "Multiplex Genome Engineering Using CRISPR/Cas Systems"
#   Humanized sequence from Patent US 12473559 B2 (Kim et al.)
#

CAS9_NATIVE = {
    "name": "SpCas9 (native S. pyogenes codons)",
    "source_organism": "Streptococcus pyogenes M1 GAS",
    "ncbi_taxonomy_id": 301447,
    "genbank_accession": "NC_002737.2 (positions 854751-858857)",
    "protein_accession": "WP_010922251.1",
    "cds_length_bp": 4107,
    "protein_length_aa": 1368,
    "dna_sequence": (
        "ATGGATAAGAAATACTCAATAGGCTTAGATATCGGCACAAATAGCGTCGGATGGGCGGTGATCACTGATG"
        "AATATAAGGTTCCGTCTAAAAAGTTCAAGGTTCTGGGAAATACAGACCGCCACAGTATCAAAAAAAATCT"
        "TATAGGGGCTCTTTTATTTGACAGTGGAGAGACAGCGGAAGCGACTCGTCTCAAACGGACAGCTCGTAGA"
        "AGGTATACACGTCGGAAGAATCGTATTTGTTATCTACAGGAGATTTTTTCAAATGAGATGGCGAAAGTAG"
        "ATGATAGTTTCTTTCATCGACTTGAAGAGTCTTTTTTGGTGGAAGAAGACAAGAAGCATGAACGTCATCC"
        "TATTTTTGGAAATATAGTAGATGAAGTTGCTTATCATGAGAAATATCCAACTATCTATCATCTGCGAAAA"
        "AAATTGGTAGATTCTACTGATAAAGCGGATTTGCGCTTAATCTATTTGGCCTTAGCGCATATGATTAAGT"
        "TTCGTGGTCATTTTTTGATTGAGGGAGATTTAAATCCTGATAATAGTGATGTGGACAAACTATTTATCCA"
        "GTTGGTACAAACCTACAATCAATTATTTGAAGAAAACCCTATTAACGCAAGTGGAGTAGATGCTAAAGCG"
        "ATTCTTTCTGCACGATTGAGTAAATCAAGACGATTAGAAAATCTCATTGCTCAGCTCCCCGGTGAGAAGA"
        "AAAATGGCTTATTTGGGAATCTCATTGCTTTGTCATTGGGTTTGACCCCTAATTTTAAATCAAATTTTGA"
        "TTTGGCAGAAGATGCTAAATTACAGCTTTCAAAAGATACTTACGATGATGATTTAGATAATTTATTGGCG"
        "CAAATTGGAGATCAATATGCTGATTTGTTTTTGGCAGCTAAGAATTTATCAGATGCTATTTTACTTTCAG"
        "ATATCCTAAGAGTAAATACTGAAATAACTAAGGCTCCCCTATCAGCTTCAATGATTAAACGCTACGATGA"
        "ACATCATCAAGACTTGACTCTTTTAAAAGCTTTAGTTCGACAACAACTTCCAGAAAAGTATAAAGAAATC"
        "TTTTTTGATCAATCAAAAAACGGATATGCAGGTTATATTGATGGGGGAGCTAGCCAAGAAGAATTTTATA"
        "AATTTATCAAACCAATTTTAGAAAAAATGGATGGTACTGAGGAATTATTGGTGAAACTAAATCGTGAAGA"
        "TTTGCTGCGCAAGCAACGGACCTTTGACAACGGCTCTATTCCCCATCAAATTCACTTGGGTGAGCTGCAT"
        "GCTATTTTGAGAAGACAAGAAGACTTTTATCCATTTTTAAAAGACAATCGTGAGAAGATTGAAAAAATCT"
        "TGACTTTTCGAATTCCTTATTATGTTGGTCCATTGGCGCGTGGCAATAGTCGTTTTGCATGGATGACTCG"
        "GAAGTCTGAAGAAACAATTACCCCATGGAATTTTGAAGAAGTTGTCGATAAAGGTGCTTCAGCTCAATCA"
        "TTTATTGAACGCATGACAAACTTTGATAAAAATCTTCCAAATGAAAAAGTACTACCAAAACATAGTTTGC"
        "TTTATGAGTATTTTACGGTTTATAACGAATTGACAAAGGTCAAATATGTTACTGAAGGAATGCGAAAACC"
        "AGCATTTCTTTCAGGTGAACAGAAGAAAGCCATTGTTGATTTACTCTTCAAAACAAATCGAAAAGTAACC"
        "GTTAAGCAATTAAAAGAAGATTATTTCAAAAAAATAGAATGTTTTGATAGTGTTGAAATTTCAGGAGTTG"
        "AAGATAGATTTAATGCTTCATTAGGTACCTACCATGATTTGCTAAAAATTATTAAAGATAAAGATTTTTT"
        "GGATAATGAAGAAAATGAAGATATCTTAGAGGATATTGTTTTAACATTGACCTTATTTGAAGATAGGGAG"
        "ATGATTGAGGAAAGACTTAAAACATATGCTCACCTCTTTGATGATAAGGTGATGAAACAGCTTAAACGTC"
        "GCCGTTATACTGGTTGGGGACGTTTGTCTCGAAAATTGATTAATGGTATTAGGGATAAGCAATCTGGCAA"
        "AACAATATTAGATTTTTTGAAATCAGATGGTTTTGCCAATCGCAATTTTATGCAGCTGATCCATGATGAT"
        "AGTTTGACATTTAAAGAAGACATTCAAAAAGCACAAGTGTCTGGACAAGGCGATAGTTTACATGAACATA"
        "TTGCAAATTTAGCTGGTAGCCCTGCTATTAAAAAAGGTATTTTACAGACTGTAAAAGTTGTTGATGAATT"
        "GGTCAAAGTAATGGGGCGGCATAAGCCAGAAAATATCGTTATTGAAATGGCACGTGAAAATCAGACAACT"
        "CAAAAGGGCCAGAAAAATTCGCGAGAGCGTATGAAACGAATCGAAGAAGGTATCAAAGAATTAGGAAGTC"
        "AGATTCTTAAAGAGCATCCTGTTGAAAATACTCAATTGCAAAATGAAAAGCTCTATCTCTATTATCTCCA"
        "AAATGGAAGAGACATGTATGTGGACCAAGAATTAGATATTAATCGTTTAAGTGATTATGATGTCGATCAC"
        "ATTGTTCCACAAAGTTTCCTTAAAGACGATTCAATAGACAATAAGGTCTTAACGCGTTCTGATAAAAATC"
        "GTGGTAAATCGGATAACGTTCCAAGTGAAGAAGTAGTCAAAAAGATGAAAAACTATTGGAGACAACTTCT"
        "AAACGCCAAGTTAATCACTCAACGTAAGTTTGATAATTTAACGAAAGCTGAACGTGGAGGTTTGAGTGAA"
        "CTTGATAAAGCTGGTTTTATCAAACGCCAATTGGTTGAAACTCGCCAAATCACTAAGCATGTGGCACAAA"
        "TTTTGGATAGTCGCATGAATACTAAATACGATGAAAATGATAAACTTATTCGAGAGGTTAAAGTGATTAC"
        "CTTAAAATCTAAATTAGTTTCTGACTTCCGAAAAGATTTCCAATTCTATAAAGTACGTGAGATTAACAAT"
        "TACCATCATGCCCATGATGCGTATCTAAATGCCGTCGTTGGAACTGCTTTGATTAAGAAATATCCAAAAC"
        "TTGAATCGGAGTTTGTCTATGGTGATTATAAAGTTTATGATGTTCGTAAAATGATTGCTAAGTCTGAGCA"
        "AGAAATAGGCAAAGCAACCGCAAAATATTTCTTTTACTCTAATATCATGAACTTCTTCAAAACAGAAATT"
        "ACACTTGCAAATGGAGAGATTCGCAAACGCCCTCTAATCGAAACTAATGGGGAAACTGGAGAAATTGTCT"
        "GGGATAAAGGGCGAGATTTTGCCACAGTGCGCAAAGTATTGTCCATGCCCCAAGTCAATATTGTCAAGAA"
        "AACAGAAGTACAGACAGGCGGATTCTCCAAGGAGTCAATTTTACCAAAAAGAAATTCGGACAAGCTTATT"
        "GCTCGTAAAAAAGACTGGGATCCAAAAAAATATGGTGGTTTTGATAGTCCAACGGTAGCTTATTCAGTCC"
        "TAGTGGTTGCTAAGGTGGAAAAAGGGAAATCGAAGAAGTTAAAATCCGTTAAAGAGTTACTAGGGATCAC"
        "AATTATGGAAAGAAGTTCCTTTGAAAAAAATCCGATTGACTTTTTAGAAGCTAAAGGATATAAGGAAGTT"
        "AAAAAAGACTTAATCATTAAACTACCTAAATATAGTCTTTTTGAGTTAGAAAACGGTCGTAAACGGATGC"
        "TGGCTAGTGCCGGAGAATTACAAAAAGGAAATGAGCTGGCTCTGCCAAGCAAATATGTGAATTTTTTATA"
        "TTTAGCTAGTCATTATGAAAAGTTGAAGGGTAGTCCAGAAGATAACGAACAAAAACAATTGTTTGTGGAG"
        "CAGCATAAGCATTATTTAGATGAGATTATTGAGCAAATCAGTGAATTTTCTAAGCGTGTTATTTTAGCAG"
        "ATGCCAATTTAGATAAAGTTCTTAGTGCATATAACAAACATAGAGACAAACCAATACGTGAACAAGCAGA"
        "AAATATTATTCATTTATTTACGTTGACGAATCTTGGAGCTCCCGCTGCTTTTAAATATTTTGATACAACA"
        "ATTGATCGTAAACGATATACGTCTACAAAAGAAGTTTTAGATGCCACTCTTATCCATCAATCCATCACTG"
        "GTCTTTATGAAACACGCATTGATTTGAGTCAGCTAGGAGGTGACTGA"
    ),
    "protein_sequence": (
        "MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEATRLKRTARR"
        "RYTRRKNRICYLQEIFSNEMAKVDDSFFHRLEESFLVEEDKKHERHPIFGNIVDEVAYHEKYPTIYHLRK"
        "KLVDSTDKADLRLIYLALAHMIKFRGHFLIEGDLNPDNSDVDKLFIQLVQTYNQLFEENPINASGVDAKA"
        "ILSARLSKSRRLENLIAQLPGEKKNGLFGNLIALSLGLTPNFKSNFDLAEDAKLQLSKDTYDDDLDNLLA"
        "QIGDQYADLFLAAKNLSDAILLSDILRVNTEITKAPLSASMIKRYDEHHQDLTLLKALVRQQLPEKYKEI"
        "FFDQSKNGYAGYIDGGASQEEFYKFIKPILEKMDGTEELLVKLNREDLLRKQRTFDNGSIPHQIHLGELH"
        "AILRRQEDFYPFLKDNREKIEKILTFRIPYYVGPLARGNSRFAWMTRKSEETITPWNFEEVVDKGASAQS"
        "FIERMTNFDKNLPNEKVLPKHSLLYEYFTVYNELTKVKYVTEGMRKPAFLSGEQKKAIVDLLFKTNRKVT"
        "VKQLKEDYFKKIECFDSVEISGVEDRFNASLGTYHDLLKIIKDKDFLDNEENEDILEDIVLTLTLFEDRE"
        "MIEERLKTYAHLFDDKVMKQLKRRRYTGWGRLSRKLINGIRDKQSGKTILDFLKSDGFANRNFMQLIHDD"
        "SLTFKEDIQKAQVSGQGDSLHEHIANLAGSPAIKKGILQTVKVVDELVKVMGRHKPENIVIEMARENQTT"
        "QKGQKNSRERMKRIEEGIKELGSQILKEHPVENTQLQNEKLYLYYLQNGRDMYVDQELDINRLSDYDVDH"
        "IVPQSFLKDDSIDNKVLTRSDKNRGKSDNVPSEEVVKKMKNYWRQLLNAKLITQRKFDNLTKAERGGLSE"
        "LDKAGFIKRQLVETRQITKHVAQILDSRMNTKYDENDKLIREVKVITLKSKLVSDFRKDFQFYKVREINN"
        "YHHAHDAYLNAVVGTALIKKYPKLESEFVYGDYKVYDVRKMIAKSEQEIGKATAKYFFYSNIMNFFKTEI"
        "TLANGEIRKRPLIETNGETGEIVWDKGRDFATVRKVLSMPQVNIVKKTEVQTGGFSKESILPKRNSDKLI"
        "ARKKDWDPKKYGGFDSPTVAYSVLVVAKVEKGKSKKLKSVKELLGITIMERSSFEKNPIDFLEAKGYKEV"
        "KKDLIIKLPKYSLFELENGRKRMLASAGELQKGNELALPSKYVNFLYLASHYEKLKGSPEDNEQKQLFVE"
        "QHKHYLDEIIEQISEFSKRVILADANLDKVLSAYNKHRDKPIREQAENIIHLFTLTNLGAPAAFKYFDTT"
        "IDRKRYTSTKEVLDATLIHQSITGLYETRIDLSQLGGD"
    ),
}

CAS9_HUMAN_OPTIMIZED = {
    "name": "SpCas9 (human codon-optimized)",
    "source_organism": "Streptococcus pyogenes (synthetic)",
    "target_organism": "Homo sapiens",
    "target_taxonomy_id": 9606,
    "genbank_accession": "PY476876.1 (Patent US 12473559 B2, Cas9 CDS portion)",
    "cds_note": "Extracted Cas9 CDS from patent construct; ATG prepended since original is a fusion protein. Encodes identical protein to native SpCas9.",
    "cds_length_bp": 4107,
    "protein_length_aa": 1368,
    "dna_sequence": (
        "ATGGACAAGAAGTACAGCATCGGCCTGGACATCGGTACCAACAGCGTGGGCTGGGCCGTGATCACCGACG"
        "AGTACAAGGTGCCCAGCAAGAAGTTCAAGGTGCTGGGCAACACCGACCGCCACAGCATCAAGAAGAACCT"
        "GATCGGCGCCCTGCTGTTCGACAGCGGCGAGACCGCCGAGGCCACCCGCCTGAAGCGCACCGCCCGCCGC"
        "CGCTACACCCGCCGCAAGAACCGCATCTGCTACCTGCAGGAGATCTTCAGCAACGAGATGGCCAAGGTGG"
        "ACGACAGCTTCTTCCACCGCCTGGAGGAGAGCTTCCTGGTGGAGGAGGACAAGAAGCACGAGCGCCACCC"
        "CATCTTCGGCAACATCGTGGACGAGGTGGCCTACCACGAGAAGTACCCCACCATCTACCACCTGCGCAAG"
        "AAGCTGGTGGACAGCACCGACAAGGCCGACCTGCGCCTGATCTACCTGGCCCTGGCCCACATGATCAAGT"
        "TCCGCGGCCACTTCCTGATCGAGGGCGACCTGAACCCCGACAACAGCGACGTGGACAAGCTGTTCATCCA"
        "GCTGGTGCAGACCTACAACCAGCTGTTCGAGGAGAACCCCATCAACGCCAGCGGCGTGGACGCCAAGGCC"
        "ATCCTGAGCGCCCGCCTGAGCAAGAGCCGCCGCCTGGAGAACCTGATCGCCCAGCTGCCCGGCGAGAAGA"
        "AGAACGGCCTGTTCGGCAACCTGATCGCCCTGAGCCTGGGCCTGACCCCCAACTTCAAGAGCAACTTCGA"
        "CCTGGCCGAGGACGCCAAGCTGCAGCTGAGCAAGGACACCTACGACGACGACCTGGACAACCTGCTGGCC"
        "CAGATCGGCGACCAGTACGCCGACCTGTTCCTGGCCGCCAAGAACCTGAGCGACGCCATCCTGCTGAGCG"
        "ACATCCTGCGCGTGAACACCGAGATCACCAAGGCCCCCCTGAGCGCCAGCATGATCAAGCGCTACGACGA"
        "GCACCACCAGGACCTGACCCTGCTGAAGGCCCTGGTGCGCCAGCAGCTGCCCGAGAAGTACAAGGAGATC"
        "TTCTTCGACCAGAGCAAGAACGGCTACGCCGGCTACATCGACGGCGGCGCCAGCCAGGAGGAGTTCTACA"
        "AGTTCATCAAGCCCATCCTGGAGAAGATGGACGGCACCGAGGAGCTGCTGGTGAAGCTGAACCGCGAGGA"
        "CCTGCTGCGCAAGCAGCGCACCTTCGACAACGGCAGCATCCCCCACCAGATCCACCTGGGCGAGCTGCAC"
        "GCCATCCTGCGCCGCCAGGAGGACTTCTACCCCTTCCTGAAGGACAACCGCGAGAAGATCGAGAAGATCC"
        "TGACCTTCCGCATCCCCTACTACGTGGGCCCCCTGGCCCGCGGCAACAGCCGCTTCGCCTGGATGACCCG"
        "CAAGAGCGAGGAGACCATCACCCCCTGGAACTTCGAGGAGGTGGTGGACAAGGGCGCCAGCGCCCAGAGC"
        "TTCATCGAGCGCATGACCAACTTCGACAAGAACCTGCCCAACGAGAAGGTGCTGCCCAAGCACAGCCTGC"
        "TGTACGAGTACTTCACCGTGTACAACGAGCTGACCAAGGTGAAGTACGTGACCGAGGGCATGCGCAAGCC"
        "CGCCTTCCTGAGCGGCGAGCAGAAGAAGGCCATCGTGGACCTGCTGTTCAAGACCAACCGCAAGGTGACC"
        "GTGAAGCAGCTGAAGGAGGACTACTTCAAGAAGATCGAGTGCTTCGACAGCGTGGAGATCAGCGGCGTGG"
        "AGGACCGCTTCAACGCCAGCCTGGGCACCTACCACGACCTGCTGAAGATCATCAAGGACAAGGACTTCCT"
        "GGACAACGAGGAGAACGAGGACATCCTGGAGGACATCGTGCTGACCCTGACCCTGTTCGAGGACCGCGAG"
        "ATGATCGAGGAGCGCCTGAAGACCTACGCCCACCTGTTCGACGACAAGGTGATGAAGCAGCTGAAGCGCC"
        "GCCGCTACACCGGCTGGGGCCGCCTGAGCCGCAAGCTTATCAACGGCATCCGCGACAAGCAGAGCGGCAA"
        "GACCATCCTGGACTTCCTGAAGAGCGACGGCTTCGCCAACCGCAACTTCATGCAGCTGATCCACGACGAC"
        "AGCCTGACCTTCAAGGAGGACATCCAGAAGGCCCAGGTGAGCGGCCAGGGCGACAGCCTGCACGAGCACA"
        "TCGCCAACCTGGCCGGCAGCCCCGCCATCAAGAAGGGCATCCTGCAGACCGTGAAGGTGGTGGACGAGCT"
        "GGTGAAGGTGATGGGCCGCCACAAGCCCGAGAACATCGTGATCGAGATGGCCCGCGAGAACCAGACCACC"
        "CAGAAGGGCCAGAAGAACAGCCGCGAGCGCATGAAGCGCATCGAGGAGGGCATCAAGGAGCTGGGCAGCC"
        "AGATCCTGAAGGAGCACCCCGTGGAGAACACCCAGCTGCAGAACGAGAAGCTGTACCTGTACTACCTGCA"
        "GAACGGCCGCGACATGTACGTGGACCAGGAGCTGGACATCAACCGCCTGAGCGACTACGACGTGGACCAC"
        "ATCGTGCCCCAGAGCTTCCTGAAGGACGACAGCATCGACAACAAGGTGCTGACCCGCAGCGACAAGAACC"
        "GCGGCAAGAGCGACAACGTGCCCAGCGAGGAGGTGGTGAAGAAGATGAAGAACTACTGGCGCCAGCTGCT"
        "GAACGCCAAGCTGATCACCCAGCGCAAGTTCGACAACCTGACCAAGGCCGAGCGCGGCGGCCTGAGCGAG"
        "CTGGACAAGGCCGGCTTCATCAAGCGCCAGCTGGTGGAGACCCGCCAGATCACCAAGCACGTGGCCCAGA"
        "TCCTGGACAGCCGCATGAACACCAAGTACGACGAGAACGACAAGCTGATCCGCGAGGTGAAGGTGATCAC"
        "CCTGAAGAGCAAGCTGGTGAGCGACTTCCGCAAGGACTTCCAGTTCTACAAGGTGCGCGAGATCAACAAC"
        "TACCACCACGCCCACGACGCCTACCTGAACGCCGTGGTGGGCACCGCCCTGATCAAGAAGTACCCCAAGC"
        "TGGAGAGCGAGTTCGTGTACGGCGACTACAAGGTGTACGACGTGCGCAAGATGATCGCCAAGAGCGAGCA"
        "GGAGATCGGCAAGGCCACCGCCAAGTACTTCTTCTACAGCAACATCATGAACTTCTTCAAGACCGAGATC"
        "ACCCTGGCCAACGGCGAGATCCGCAAGCGCCCCCTGATCGAGACCAACGGCGAGACCGGCGAGATCGTGT"
        "GGGACAAGGGCCGCGACTTCGCCACCGTGCGCAAGGTGCTGAGCATGCCCCAGGTGAACATCGTGAAGAA"
        "GACCGAGGTGCAGACCGGCGGCTTCAGCAAGGAGAGCATCCTGCCCAAGCGCAACAGCGACAAGCTGATC"
        "GCCCGCAAGAAGGACTGGGACCCCAAGAAGTACGGCGGCTTCGACAGCCCCACCGTGGCCTACAGCGTGC"
        "TGGTGGTGGCCAAGGTGGAGAAGGGCAAGAGCAAGAAGCTGAAGAGCGTGAAGGAGCTGCTGGGCATCAC"
        "CATCATGGAGCGCAGCAGCTTCGAGAAGAACCCCATCGACTTCCTGGAGGCCAAGGGCTACAAGGAGGTG"
        "AAGAAGGACCTGATCATCAAGCTGCCCAAGTACAGCCTGTTCGAGCTGGAGAACGGCCGCAAGCGCATGC"
        "TGGCCAGCGCCGGCGAGCTGCAGAAGGGCAACGAGCTGGCCCTGCCCAGCAAGTACGTGAACTTCCTGTA"
        "CCTGGCCAGCCACTACGAGAAGCTGAAGGGCAGCCCCGAGGACAACGAGCAGAAGCAGCTGTTCGTGGAG"
        "CAGCACAAGCACTACCTGGACGAGATCATCGAGCAGATCAGCGAGTTCAGCAAGCGCGTGATCCTGGCCG"
        "ACGCCAACCTGGACAAGGTGCTGAGCGCCTACAACAAGCACCGCGACAAGCCCATCCGCGAGCAGGCCGA"
        "GAACATCATCCACCTGTTCACCCTGACCAACCTGGGCGCCCCCGCCGCCTTCAAGTACTTCGACACCACC"
        "ATCGACCGCAAGCGCTACACCAGCACCAAGGAGGTGCTGGACGCCACCCTGATCCACCAGAGCATCACCG"
        "GTCTGTACGAGACCCGCATCGACCTGAGCCAGCTGGGCGGCGACTAA"
    ),
    "protein_sequence": (
        "MDKKYSIGLDIGTNSVGWAVITDEYKVPSKKFKVLGNTDRHSIKKNLIGALLFDSGETAEATRLKRTARR"
        "RYTRRKNRICYLQEIFSNEMAKVDDSFFHRLEESFLVEEDKKHERHPIFGNIVDEVAYHEKYPTIYHLRK"
        "KLVDSTDKADLRLIYLALAHMIKFRGHFLIEGDLNPDNSDVDKLFIQLVQTYNQLFEENPINASGVDAKA"
        "ILSARLSKSRRLENLIAQLPGEKKNGLFGNLIALSLGLTPNFKSNFDLAEDAKLQLSKDTYDDDLDNLLA"
        "QIGDQYADLFLAAKNLSDAILLSDILRVNTEITKAPLSASMIKRYDEHHQDLTLLKALVRQQLPEKYKEI"
        "FFDQSKNGYAGYIDGGASQEEFYKFIKPILEKMDGTEELLVKLNREDLLRKQRTFDNGSIPHQIHLGELH"
        "AILRRQEDFYPFLKDNREKIEKILTFRIPYYVGPLARGNSRFAWMTRKSEETITPWNFEEVVDKGASAQS"
        "FIERMTNFDKNLPNEKVLPKHSLLYEYFTVYNELTKVKYVTEGMRKPAFLSGEQKKAIVDLLFKTNRKVT"
        "VKQLKEDYFKKIECFDSVEISGVEDRFNASLGTYHDLLKIIKDKDFLDNEENEDILEDIVLTLTLFEDRE"
        "MIEERLKTYAHLFDDKVMKQLKRRRYTGWGRLSRKLINGIRDKQSGKTILDFLKSDGFANRNFMQLIHDD"
        "SLTFKEDIQKAQVSGQGDSLHEHIANLAGSPAIKKGILQTVKVVDELVKVMGRHKPENIVIEMARENQTT"
        "QKGQKNSRERMKRIEEGIKELGSQILKEHPVENTQLQNEKLYLYYLQNGRDMYVDQELDINRLSDYDVDH"
        "IVPQSFLKDDSIDNKVLTRSDKNRGKSDNVPSEEVVKKMKNYWRQLLNAKLITQRKFDNLTKAERGGLSE"
        "LDKAGFIKRQLVETRQITKHVAQILDSRMNTKYDENDKLIREVKVITLKSKLVSDFRKDFQFYKVREINN"
        "YHHAHDAYLNAVVGTALIKKYPKLESEFVYGDYKVYDVRKMIAKSEQEIGKATAKYFFYSNIMNFFKTEI"
        "TLANGEIRKRPLIETNGETGEIVWDKGRDFATVRKVLSMPQVNIVKKTEVQTGGFSKESILPKRNSDKLI"
        "ARKKDWDPKKYGGFDSPTVAYSVLVVAKVEKGKSKKLKSVKELLGITIMERSSFEKNPIDFLEAKGYKEV"
        "KKDLIIKLPKYSLFELENGRKRMLASAGELQKGNELALPSKYVNFLYLASHYEKLKGSPEDNEQKQLFVE"
        "QHKHYLDEIIEQISEFSKRVILADANLDKVLSAYNKHRDKPIREQAENIIHLFTLTNLGAPAAFKYFDTT"
        "IDRKRYTSTKEVLDATLIHQSITGLYETRIDLSQLGGD"
    ),
}


# =============================================================================
# TEST CASE 7: Alginate Lyase Codon Optimization (Marine metagenome -> E. coli)
# =============================================================================
#
# An alginate lyase from a marine metagenome, codon-optimized for E. coli
# expression. This is a non-model-organism microbial enzyme expressed in a
# microbial host — a common industrial biotechnology use case.
#
# GenBank: PQ118945.1
#

ALGINATE_LYASE_ECOLI = {
    "name": "Alginate lyase (E. coli codon-optimized, from marine metagenome)",
    "source_organism": "Marine metagenome (uncultured bacterium)",
    "target_organism": "Escherichia coli",
    "target_taxonomy_id": 316407,
    "genbank_accession": "PQ118945.1",
    "cds_note": "Contains C-terminal His-tag; IMG genome ID 3300002242",
    "cds_length_bp": 774,
    "protein_length_aa": 257,
    "dna_sequence": (
        "ATGTACCCGAGCGATATTCTGCCGAATCTGAATAAATGGTATCTGACCCTGCCGGTTGAT"
        "AGTAATGGTAATACCAGCGCCGGTGCAACCAATGTTGAAAATCGTAATACCAATCCGCTG"
        "CTGATTAAAGGCAATGCACTGATTAATTATGAGTATCCGCCGTACTTCGATGTGATTGAT"
        "AGTGCAGTGGTGTTCCGTGCACCGTGCGATGGTGCCACCACCACCGGTAGTAATTATCCG"
        "CGTTGCGAACTGCGCGAACTGGTTGGCGGTGGCACCAATTATTGGAGCGTGAATGACTTC"
        "CAGTTCCTGCAGGCAGAACTGAAAGTGACCCATCTGCCGGATGTTAAACCGGATGTGTGC"
        "TTCACCCAGATTCATGCACCGGGCCATCATGAACCGCTGCGCCTGCATTATAATGCAACC"
        "AAAGGCCTGTATATTGTGAGTAATACCACCAATCATTACTATATTAAGGACGATGTGCCGT"
        "ATAGTCTGGGTCAGACCCTGCTGATTAAGGTTGCCGTGCAGAATGGCACCATTACCTGCTT"
        "CATTAAAAATATTGCAAACGGTAAGCAGACCGTGCGTACCTGGAAAAGTGATCAGACCACC"
        "GGCTACTTCAAAATTGGTTGCTATACCCAGAGCAGTATCTTCCTGAGCCAGTTCAAAAAA"
        "GGCTATCAGAATGAACCGATGGATGCATACGGTGAAGTGCGCGTTCTGAAACTGAGTAT"
        "TGTGGAAACCTATAATCAGGATAAACTCGAGCACCACCACCACCACCACTGA"
    ),
    "protein_sequence": (
        "MYPSDILPNLNKWYLTLPVDSNGNTSAGATNVENRNTNPLLIKGNALINYEYPPYFDVID"
        "SAVVFRAPCDGATTTGSNYPRCELRELVGGGTNYWSVNDFQFLQAELKVTHLPDVKPDVCF"
        "TQIHAPGHHEPLRLHYNATKGLYIVSNTTNHYYIKDDVPYSLGQTLLIKVAVQNGTITCF"
        "IKNIANGKQTVRTWKSDQTTGYFKIGCYTQSSIFLSQFKKGYQNEPMDAYGEVRVLKLSI"
        "VETYNQDKLEHHHHHH"
    ),
}

# =============================================================================
# TEST CASE 8: MSP1-42 3D7 Codon Harmonization (P. falciparum 3D7 -> E. coli)
# =============================================================================
#
# A second MSP1-42 harmonization example from the Angov et al. (2008) paper,
# using the 3D7 strain instead of FVO. Demonstrates that the harmonization
# algorithm produces strain-specific results even for the same protein family.
#
# Reference: Angov et al. (2008) PLoS ONE 3(5):e2189
#

MSP142_3D7_HARMONIZED = {
    "name": "MSP1-42 3D7 (codon-harmonized for E. coli)",
    "source_organism": "Plasmodium falciparum 3D7 (synthetic)",
    "target_organism": "Escherichia coli",
    "target_taxonomy_id": 562,
    "genbank_accession": "DQ926901",
    "cds_note": "Full construct has N-terminal His-tag. MSP1-42 3D7 variant.",
    "full_length_bp": 1170,
    "dna_sequence_full_construct": (
        "ATGGCACACCATCATCATCATCATCCCGGGGGATCCGGTTCTGGTACCATGGCTATTAGCG"
        "TCACTATGGACAATATATTAAGCGGCTTCGAAAACGAATACGACGTTATCTACCTGAAACC"
        "ACTGGCTGGCGTTTACCGTTCGCTGAAAAAACAGATTGAAAAAAATATTTTCACCTTCAAC"
        "CTGAACCTCAATGACATACTGAACAGCCGACTCAAGAAACGAAAATACTTTCTGGACGTTC"
        "TGGAAAGCGACCTGATGCAGTTCAAACACATTTCGAGCAACGAATATATTATTGAAGACAG"
        "CTTCAAACTGCTCAACAGCGAACAGAAAAATACCCTCCTGAAATCTTATAAATACATCAAA"
        "GAAAGCGTTGAAAACGACATTAAATTCGCTCAAGAAGGCATCTCTTACTACGAAAAGGTTC"
        "TGGCCAAATACAAGGACGACCTGGAAAGCATTAAAAAAGTTATAAAAGAAGAAAAGGAGAAG"
        "TTTCCAAGCAGCCCACCAACCACTCCACCCAGCCCAGCTAAAACCGATGAACAGAAGAAGGA"
        "AAGCAAGTTTCTCCCATTCCTGACCAATATTGAGACGCTGTATAACAATCTGGTTAACAAAA"
        "TTGATGACTATCTGATTAATCTGAAGGCTAAGATTAATGACTGCAACGTTGAAAAAGACGA"
        "AGCTCACGTTAAAATCACTAAACTCTCTGACCTGAAAGCTATTGACGATAAAATCGACCTCT"
        "TCAAAAATCCAACGGATTTTGAAGCTATTAAAAAACTCATCAACGACGACACGAAAAAAGAC"
        "ATGCTCGGGAAACTGCTCTCTACCGGCCTGGTTCAGAATTTCCCAAACACCATCATCAGCAA"
        "ACTGATTGAAGGCAAATTTCAGGACATGCTGAATATTAGCCAGCATCAGTGTGTTAAAAAA"
        "CAGTGCCCAGAAAACAGCGGCTGCTTTCGTCACCTGGACGAACGTGAAGAATGCAAATGCC"
        "TGCTGAACTATAAACAGGAAGGCGACAAATGCGTTGAAAACCCAAACCCAACTTGCAATGA"
        "AAACAACGGCGGCTGCGACGCTGACGCCACCTGCACGGAAGAAGACAGCGGCTCGTCGCGT"
        "AAGAAAATAACCTGCGAATGCACTAAACCAGACAGCTACCCACTCTTTGACGGCATTTTTTG"
        "TAGC"
    ),
    "protein_sequence_full": (
        "MAHHHHHHPGGSGSGTMAISVTMDNILSGFENEYDVIYLKPLAGVYRSLKKQIEKNIFTFN"
        "LNLNDILNSRLKKRKYFLDVLESDLMQFKHISSNEYIIEDSFKLLNSEQKNTLLKSYKYIK"
        "ESVENDIKFAQEGISYYEKVLAKYKDDLESIKKVIKEEKEKFPSSPPTTPPSPAKTDEQKKE"
        "SKFLPFLTNIETLYNNLVNKIDDYLINLKAKINDCNVEKDEAHVKITKLSDLKAIDDKIDL"
        "FKNPTDFEAIKKLINDDTKKDMLGKLLSTGLVQNFPNTIISKLIEGKFQDMLNISQHQCVK"
        "KQCPENSGCFRHLDEREECKCLLNYKQEGDKCVENPNPTCNENNGGCDADATCTEEDSGSSR"
        "KKITCECTKPDSYPLFDGIFCS"
    ),
}

# =============================================================================
# CONVENIENCE: Paired test cases for optimization/harmonization testing
# =============================================================================

CODON_OPTIMIZATION_PAIRS = [
    {
        "name": "GFP -> EGFP (codon optimization + mutations, jellyfish -> human)",
        "type": "optimization_with_mutations",
        "native": GFP_WILD_TYPE,
        "optimized": EGFP_HUMANIZED,
        "same_protein": False,  # EGFP has F64L, S65T, V2ins
    },
    {
        "name": "MSP1-42 codon harmonization (P. falciparum -> E. coli)",
        "type": "harmonization",
        "native": MSP142_NATIVE,
        "optimized": MSP142_HARMONIZED,
        "same_protein": True,  # Identical proteins
    },
    {
        "name": "SpCas9 codon optimization (S. pyogenes -> Human)",
        "type": "optimization",
        "native": CAS9_NATIVE,
        "optimized": CAS9_HUMAN_OPTIMIZED,
        "same_protein": True,  # Identical proteins
    },
]

# GFP variants optimized for different organisms (same/similar protein,
# different codon usage). Useful for comparing CAI across organisms.
GFP_MULTI_ORGANISM = {
    "wild_type_jellyfish": GFP_WILD_TYPE,          # Aequorea victoria (native)
    "human_optimized": EGFP_HUMANIZED,               # Homo sapiens (high GC)
    "yeast_optimized": YEGFP3_YEAST,                 # S. cerevisiae (moderate GC)
    "gram_positive_optimized": GFPOPT_GRAM_POSITIVE,  # B. anthracis (low GC)
}

# Pairs with IDENTICAL proteins (pure synonymous codon changes)
SYNONYMOUS_PAIRS = [
    pair for pair in CODON_OPTIMIZATION_PAIRS if pair["same_protein"]
]

# All individual sequences for non-paired testing (e.g., CAI analysis,
# re-optimization with our tool, etc.)
ALL_SEQUENCES = {
    "gfp_wild_type": GFP_WILD_TYPE,
    "egfp_human": EGFP_HUMANIZED,
    "gfpopt_gram_positive": GFPOPT_GRAM_POSITIVE,
    "yegfp3_yeast": YEGFP3_YEAST,
    "insulin_human": INSULIN_HUMAN_NATIVE,
    "insulin_ecoli": INSULIN_ECOLI_OPTIMIZED,
    "msp142_native": MSP142_NATIVE,
    "msp142_harmonized": MSP142_HARMONIZED,
    "msp142_3d7_harmonized": MSP142_3D7_HARMONIZED,
    "cas9_native": CAS9_NATIVE,
    "cas9_human": CAS9_HUMAN_OPTIMIZED,
    "alginate_lyase_ecoli": ALGINATE_LYASE_ECOLI,
}
